!!python/object:argparse.Namespace
algo: r_gcbf+
alpha: 1.0
area_size: 4.0
buffer_size: 512
debug: false
env: DoubleIntegrator
eval_epi: 1
eval_interval: 1
gnn_layers: 1
horizon: 32
log_dir: ./logs
loss_action_coef: 0.0001
loss_h_dot_coef: 0.01
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 1.0e-05
lr_cbf: 1.0e-05
n_env_test: 32
n_env_train: 16
n_rays: 32
name: null
num_agents: 8
obs: null
save_interval: 10
seed: 0
steps: 1000
alpha: 1.0
batch_size: 256
eps: 0.02
gnn_layers: 1
horizon: 32
inner_epoch: 8
loss_action_coef: 0.0001
loss_h_dot_coef: 0.01
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 1.0e-05
lr_cbf: 1.0e-05
max_grad_norm: 2.0
seed: 0
